services:
  deliveryix-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-2019
    restart: always
    environment:
      SA_PASSWORD: "StrongPassword@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - deliveryix-sqlserver_data:/var/opt/mssql

  deliveryix-redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - deliveryix-redis_data:/data

  deliveryix-servicebus:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: servicebus-emulator
    restart: always
    depends_on:
      - deliveryix-sqlserver
    ports:
      - "5672:5672" # AMQP
      - "5300:5300" # Management API
    environment:
      SQL_SERVER: deliveryix-sqlserver
      MSSQL_SA_PASSWORD: "StrongPassword@123"
      ACCEPT_EULA: "Y"
      EMULATOR_HTTP_PORT: 5300
    volumes:
      - ./servicebus-config.json:/ServiceBus_Emulator/ConfigFiles/Config.json

volumes:
  deliveryix-sqlserver_data:
  deliveryix-redis_data:
