// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Identity.Infrastructure.Database;

#nullable disable

namespace Modules.Identity.Infrastructure.Database.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deliveryix.Commons.Infrastructure.Inbox.Models.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Error")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages", "identity");
                });

            modelBuilder.Entity("Deliveryix.Commons.Infrastructure.Inbox.Models.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(256)");

                    b.HasKey("Id", "Name");

                    b.ToTable("InboxMessageConsumers", "identity");
                });

            modelBuilder.Entity("Deliveryix.Commons.Infrastructure.Outbox.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Error")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "identity");
                });

            modelBuilder.Entity("Deliveryix.Commons.Infrastructure.Outbox.Models.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(256)");

                    b.HasKey("Id", "Name");

                    b.ToTable("OutboxMessageConsumers", "identity");
                });

            modelBuilder.Entity("IdentityRole", b =>
                {
                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RolesName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("RoleName");

                    b.HasKey("IdentityId", "RolesName");

                    b.HasIndex("RolesName");

                    b.ToTable("IdentityRoles", "identity");
                });

            modelBuilder.Entity("Modules.Identity.Domain.Identities.Entities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdentityProviderId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn", "Id");

                    b.ToTable("Identities", "identity");
                });

            modelBuilder.Entity("Modules.Identity.Domain.Identities.Models.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Code");

                    b.ToTable("Permissions", "identity");
                });

            modelBuilder.Entity("Modules.Identity.Domain.Identities.Models.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Name");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("RoleName")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("PermissionCode", "RoleName");

                    b.HasIndex("RoleName");

                    b.ToTable("RolePermissions", "identity");
                });

            modelBuilder.Entity("IdentityRole", b =>
                {
                    b.HasOne("Modules.Identity.Domain.Identities.Entities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Identity.Domain.Identities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Identity.Domain.Identities.Entities.Identity", b =>
                {
                    b.OwnsOne("Modules.Identity.Domain.Identities.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("IdentityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("VARCHAR(160)")
                                .HasColumnName("Email");

                            b1.HasKey("IdentityId");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("IX_Identities_Email");

                            b1.ToTable("Identities", "identity");

                            b1.WithOwner()
                                .HasForeignKey("IdentityId");
                        });

                    b.OwnsOne("Modules.Identity.Domain.Identities.ValueObjects.IdentityState", "State", b1 =>
                        {
                            b1.Property<Guid>("IdentityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset?>("DeletedOn")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("DeletedOn");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("VARCHAR(80)")
                                .HasColumnName("Status");

                            b1.HasKey("IdentityId");

                            b1.ToTable("Identities", "identity");

                            b1.WithOwner()
                                .HasForeignKey("IdentityId");
                        });

                    b.OwnsOne("Modules.Identity.Domain.Identities.ValueObjects.LegalDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("IdentityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("VARCHAR(20)")
                                .HasColumnName("Document");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("VARCHAR(10)")
                                .HasColumnName("DocumentType");

                            b1.HasKey("IdentityId");

                            b1.HasIndex("Type", "Number")
                                .IsUnique();

                            b1.ToTable("Identities", "identity");

                            b1.WithOwner()
                                .HasForeignKey("IdentityId");
                        });

                    b.OwnsOne("Modules.Identity.Domain.Identities.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("IdentityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("VARCHAR(40)")
                                .HasColumnName("Phone");

                            b1.HasKey("IdentityId");

                            b1.ToTable("Identities", "identity");

                            b1.WithOwner()
                                .HasForeignKey("IdentityId");
                        });

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("State")
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Modules.Identity.Domain.Identities.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Identity.Domain.Identities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
